<?php

/**
* Class Auditorios generated by Chrysalis v.1.0.0
* 
* Chrysalis info:
* @author pabhoz
* github: @pabhoz
* bitbucket: @pabhoz
* 
*/ 
 
class Auditorios extends BModel {

    private $ID;
    private $DESCRIPTION;
    private $ID_AUDIENCE;
    private $SCHEDULES;

    public function __construct( $ID,  string $DESCRIPTION, int $ID_AUDIENCE, string $SCHEDULES) {

        parent::__construct();
        $this->ID = $ID;
        $this->DESCRIPTION = $DESCRIPTION;
        $this->ID_AUDIENCE = $ID_AUDIENCE;
        $this->SCHEDULES = $SCHEDULES;
    }

    public function getID(): int {
        return $this->ID;
    }

    public function getDESCRIPTION(): string {
        return $this->DESCRIPTION;
    }

    public function getID_AUDIENCE(): int {
        return $this->ID_AUDIENCE;
    }

    public function getSCHEDULES(): string {
        return $this->SCHEDULES;
    }

    public function setID(int $ID) {
        $this->ID = $ID;
    }

    public function setDESCRIPTION(string $DESCRIPTION) {
        $this->DESCRIPTION = $DESCRIPTION;
    }

    public function setID_AUDIENCE(int $ID_AUDIENCE) {
        $this->ID_AUDIENCE = $ID_AUDIENCE;
    }

    public function setSCHEDULES(string $SCHEDULES) {
        $this->SCHEDULES = $SCHEDULES;
    }

    public function getMyVars(){
        return get_object_vars($this);
    }

}