<?php

/**
* Class Carreras generated by Chrysalis v.1.0.0
* 
* Chrysalis info:
* @author pabhoz
* github: @pabhoz
* bitbucket: @pabhoz
* 
*/ 
 
class Carreras extends BModel {

    private $ID_CAREER;
    private $NAME;
    private $TYPE;
    private $OBJECT;
    private $ID_FACULTY;

    public function __construct( $ID_CAREER,  string $NAME, int $TYPE, string $OBJECT, int $ID_FACULTY) {

        parent::__construct();
        $this->ID_CAREER = $ID_CAREER;
        $this->NAME = $NAME;
        $this->TYPE = $TYPE;
        $this->OBJECT = $OBJECT;
        $this->ID_FACULTY = $ID_FACULTY;
    }

    public function getID_CAREER(): int {
        return $this->ID_CAREER;
    }

    public function getNAME(): string {
        return $this->NAME;
    }

    public function getTYPE(): int {
        return $this->TYPE;
    }

    public function getOBJECT(): string {
        return $this->OBJECT;
    }

    public function getID_FACULTY(): int {
        return $this->ID_FACULTY;
    }

    public function setID_CAREER(int $ID_CAREER) {
        $this->ID_CAREER = $ID_CAREER;
    }

    public function setNAME(string $NAME) {
        $this->NAME = $NAME;
    }

    public function setTYPE(int $TYPE) {
        $this->TYPE = $TYPE;
    }

    public function setOBJECT(string $OBJECT) {
        $this->OBJECT = $OBJECT;
    }

    public function setID_FACULTY(int $ID_FACULTY) {
        $this->ID_FACULTY = $ID_FACULTY;
    }

    public function getMyVars(){
        return get_object_vars($this);
    }

}