<?php

/**
* Class Directorio generated by Chrysalis v.1.0.0
* 
* Chrysalis info:
* @author pabhoz
* github: @pabhoz
* bitbucket: @pabhoz
* 
*/ 
 
class Directorio extends BModel {

    private $ID;
    private $UNIT_ID;
    private $DESCRIPTION;
    private $EMAIL;
    private $PHONE;

    public function __construct( $ID,  int $UNIT_ID, string $DESCRIPTION, string $EMAIL, string $PHONE) {

        parent::__construct();
        $this->ID = $ID;
        $this->UNIT_ID = $UNIT_ID;
        $this->DESCRIPTION = $DESCRIPTION;
        $this->EMAIL = $EMAIL;
        $this->PHONE = $PHONE;
    }

    public function getID(): int {
        return $this->ID;
    }

    public function getUNIT_ID(): int {
        return $this->UNIT_ID;
    }

    public function getDESCRIPTION(): string {
        return $this->DESCRIPTION;
    }

    public function getEMAIL(): string {
        return $this->EMAIL;
    }

    public function getPHONE(): string {
        return $this->PHONE;
    }

    public function setID(int $ID) {
        $this->ID = $ID;
    }

    public function setUNIT_ID(int $UNIT_ID) {
        $this->UNIT_ID = $UNIT_ID;
    }

    public function setDESCRIPTION(string $DESCRIPTION) {
        $this->DESCRIPTION = $DESCRIPTION;
    }

    public function setEMAIL(string $EMAIL) {
        $this->EMAIL = $EMAIL;
    }

    public function setPHONE(string $PHONE) {
        $this->PHONE = $PHONE;
    }

    public function getMyVars(){
        return get_object_vars($this);
    }

}