<?php

/**
* Class Edificiosauditorios generated by Chrysalis v.1.0.0
* 
* Chrysalis info:
* @author pabhoz
* github: @pabhoz
* bitbucket: @pabhoz
* 
*/ 
 
class Edificiosauditorios extends BModel {

    private $ID;
    private $DESCRIPTION;

    public function __construct( $ID,  string $DESCRIPTION) {

        parent::__construct();
        $this->ID = $ID;
        $this->DESCRIPTION = $DESCRIPTION;
    }

    public function getID(): int {
        return $this->ID;
    }

    public function getDESCRIPTION(): string {
        return $this->DESCRIPTION;
    }

    public function setID(int $ID) {
        $this->ID = $ID;
    }

    public function setDESCRIPTION(string $DESCRIPTION) {
        $this->DESCRIPTION = $DESCRIPTION;
    }

    public function getMyVars(){
        return get_object_vars($this);
    }

}