<?php

/**
* Class Facultades generated by Chrysalis v.1.0.0
* 
* Chrysalis info:
* @author pabhoz
* github: @pabhoz
* bitbucket: @pabhoz
* 
*/ 
 
class Facultades extends BModel {

    private $ID;
    private $NAME;
    private $OBJECT;

    public function __construct( $ID,  string $NAME, string $OBJECT) {

        parent::__construct();
        $this->ID = $ID;
        $this->NAME = $NAME;
        $this->OBJECT = $OBJECT;
    }

    public function getID(): int {
        return $this->ID;
    }

    public function getNAME(): string {
        return $this->NAME;
    }

    public function getOBJECT(): string {
        return $this->OBJECT;
    }

    public function setID(int $ID) {
        $this->ID = $ID;
    }

    public function setNAME(string $NAME) {
        $this->NAME = $NAME;
    }

    public function setOBJECT(string $OBJECT) {
        $this->OBJECT = $OBJECT;
    }

    public function getMyVars(){
        return get_object_vars($this);
    }

}